name: cd

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Experiment
      run: |
        pwd             # /home/runner/work/try/try
        mkdir hello
        cd hello
        pwd             # /home/runner/work/try/try/hello

    - name: In another step
      run: |
        pwd

